apiVersion: v1
kind: Secret
metadata:
  name: spring-datasource-secrets
type: Opaque
data:
  spring_datasource_username: ZGJfdXNlcg==
  spring_datasource_password: ZGJfcGFzc3dvcmQ=
  #jdbc:postgresql://pg-db:5432/crud
  spring_datasource_url: amRiYzpwb3N0Z3Jlc3FsOi8vcGctZGI6NTQzMi9jcnVk
