apiVersion: v1
kind: Secret
metadata:
  name: spring-datasource-secrets
type: Opaque
data:
  spring_datasource_username: ZGJfdXNlcg==
  spring_datasource_password: ZGJfcGFzc3dvcmQ=
  #jdbc:postgresql://pg-postgresql:5432/crud
  spring_datasource_url: amRiYzpwb3N0Z3Jlc3FsOi8vcGctcG9zdGdyZXNxbDo1NDMyL2NydWQK
