apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-java-app
  template:
    metadata:
      labels:
        app: crud-java-app
    spec:
      containers:
        - name: crud-java
          image: yvzhelnin/crud-app:v0.1
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          env:
            - name: spring_datasource_username
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets
                  key: spring_datasource_username
            - name: spring_datasource_password
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets
                  key: spring_datasource_password
            - name: spring_datasource_url
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets
                  key: spring_datasource_url
          livenessProbe:
            httpGet:
              port: 80
              path: /info/status
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /info/health
            initialDelaySeconds: 10
            periodSeconds: 5
