apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-appl-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-java-appl
  template:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: /actuator/prometheus
    metadata:
      labels:
        app: crud-java-appl
    spec:
      initContainers:
        - name: init-pg
          image: busybox
          command: ['sh', '-c', 'until nslookup pg-postgresql; do echo waiting for myservice; sleep 2; done;']
      containers:
        - name: crud-pod-java
          image: yvzhelnin/crud-appl:v2.1
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          env:
            - name: spring_datasource_username
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets
                  key: spring_datasource_username
            - name: spring_datasource_password
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets
                  key: spring_datasource_password
            - name: spring_datasource_url
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets
                  key: spring_datasource_url
          livenessProbe:
            httpGet:
              port: 80
              path: /info/status
            initialDelaySeconds: 50
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /info/health
            initialDelaySeconds: 40
            periodSeconds: 5
