apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label }}
    spec:
      initContainers:
        - name: {{ .Values.deployment.initContainer.name }}
          image: {{ .Values.deployment.initContainer.image }}
          command: ["sh", "-c", {{ printf "until nslookup %s-memcached; do echo waiting for memcached; sleep 2; done;" .Release.Name | quote }} ]
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.deployment.image.repo }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: {{ .Values.deployment.container.portName }}
              containerPort: {{ .Values.deployment.container.port }}
          env:
            - name: cart_cache_host
              valueFrom:
                secretKeyRef:
                  name: cart-memcached-secrets
                  key: cart_cache_host
            - name: cart_cache_port
              valueFrom:
                secretKeyRef:
                  name: cart-memcached-secrets
                  key: cart_cache_port
          livenessProbe:
            httpGet:
              port: {{ .Values.deployment.container.port }}
              path: /cart-app/info/health
            initialDelaySeconds: {{ .Values.deployment.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              port: {{ .Values.deployment.container.port }}
              path: /cart-app/info/status
            initialDelaySeconds: {{ .Values.deployment.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readiness.periodSeconds }}
