{
 "title": "CRUD App Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_seconds_count{status=~\"5.+\"}[2m]))"
    }
   ]
  },
  {
   "title": "Error Rate (Ingress)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[2m]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_seconds_count[2m]))"
    }
   ]
  },
  {
   "title": "RPS (Ingress)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[2m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(method, uri, le) (rate(http_server_requests_seconds_bucket[2m]))) * 1000"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(method, uri, le) (rate(http_server_requests_seconds_bucket[2m]))) * 1000"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(method, uri, le) (rate(http_server_requests_seconds_bucket[2m]))) * 1000"
    },
    {
     "expr": "histogram_quantile(1, sum by(method, uri, le) (rate(http_server_requests_seconds_bucket[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency (Ingress)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) "
    }
   ]
  }
 ]
}