apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.auth.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.auth.service.port }}{{ .Values.auth.url }}"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/crud-app/api/auth/signin"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              serviceName: {{ .Values.service.name }}
              servicePort: {{ .Values.service.port }}
