apiVersion: v1
kind: Secret
metadata:
  name: spring-datasource-secrets
type: Opaque
data:
  spring_datasource_username: {{ .Values.deployment.dbCredentials.spring_datasource_username }}
  spring_datasource_password: {{ .Values.deployment.dbCredentials.spring_datasource_password }}
  spring_datasource_url: {{ .Values.deployment.dbCredentials.spring_datasource_url }}
