apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crud-appl-service-monitor
  namespace: crud-app
  labels:
    app: crud-appl-service-label
    release: prometheus
spec:
  jobLabel: crud-appl-service-monitor
  namespaceSelector:
    matchNames:
      - crud-app
  selector:
    matchLabels:
      app: crud-appl-service-label
  endpoints:
    - interval: 15s
      port: service-web
      path: /actuator/prometheus
