{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}-monitor
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app: {{ .Values.service.name }}-monitor
spec:
  jobLabel: {{ .Values.service.name }}-monitor-job
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  endpoints:
    - interval: 15s
      port: {{ .Values.deployment.container.portName }}
      path: /actuator/prometheus
{{- end }}
