apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
type: Opaque
data:
  spring_kafka_bootstrap_server: {{ .Values.kafka.bootstrapServer }}
  spring_kafka_producer_client_id: {{ .Values.kafka.clientId }}
  spring_kafka_consumer_group_id: {{ .Values.kafka.consumerGroup }}
  kafka_notification_topic_name: {{ .Values.kafka.notificationTopicName }}
