apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
type: Opaque
data:
  spring_kafka_bootstrap_server: {{ printf "%s-kafka:%s" .Release.Name .Values.kafka.port | b64enc }}
  spring_kafka_producer_client_id: {{ .Values.kafka.clientId | b64enc }}
  spring_kafka_consumer_group_id: {{ .Values.kafka.consumerGroup | b64enc }}
  kafka_notification_topic_name: {{ .Values.kafka.notificationTopicName | b64enc }}
