apiVersion: v1
kind: Secret
metadata:
  name: order-app-secrets
type: Opaque
data:
  billing_app_url_withdraw: {{ .Values.app.withdrawUrl | b64enc }}
  warehouse_app_url_book: {{ .Values.app.bookUrl | b64enc }}
  warehouse_app_url_unbook: {{ .Values.app.unbookUrl | b64enc }}
  cart_app_url_clear: {{ .Values.app.clearCartUrl | b64enc }}
