apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
data:
  spring_rabbitmq_server: {{ printf "%s-rabbitmq" .Release.Name | b64enc }}
  spring_rabbitmq_port: {{ .Values.rabbitmq.port | b64enc }}
  order_delivery_queue: {{ .Values.rabbitmq.deliveryQueue | b64enc }}
  order_notification_queue: {{ .Values.rabbitmq.notificationQueue | b64enc }}
