apiVersion: v2
name: crud-appl-chart
description: A Helm chart for CRUD Otus arch HW application

type: application
version: 0.1.0
appVersion: v1.5

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - pg-postgresql
