replicaCount: 2

deployment:
  name: crud-appl-deployment
  image:
    repo: yvzhelnin/crud-appl
    pullPolicy: Always
  label: crud-java-appl
  initContainer:
    name: init-pg
    image: busybox
  container:
    name: crud-pod-java
    portName: web
    port: 80
  readiness:
    initialDelaySeconds: 40
    periodSeconds: 5
    timeoutSeconds: 2
  liveness:
    initialDelaySeconds: 50
    periodSeconds: 5
service:
  name: crud-appl-service
  label: crud-appl-service-label
  type: NodePort
  protocol: TCP
  port: 8000

ingress:
  host: arch.homework
  name: crud-ingress
  path: /crud-app($|/)(.*)
  pathType: Prefix

postgresql:
  postgresqlUsername: db_user
  postgresqlPassword: db_password
  postgresqlDatabase: crud
  service:
    port: "5432"

metrics:
  serviceMonitor:
    enabled: true
