replicaCount: 1

deployment:
  name: catalog-appl-deployment
  image:
    repo: yvzhelnin/catalog-appl
    pullPolicy: Always
  label: catalog-java-appl
  initContainer:
    name: init-pg
    image: busybox
  container:
    name: catalog-pod-java
    portName: web
    port: 80
  readiness:
    initialDelaySeconds: 40
    periodSeconds: 5
    timeoutSeconds: 2
  liveness:
    initialDelaySeconds: 50
    periodSeconds: 5
service:
  name: catalog-appl-service
  label: catalog-appl-service-label
  type: NodePort
  protocol: TCP
  portName: service-web
  port: 8000

ingress:
  host: arch.homework
  name: catalog-ingress
