apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label }}
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.deployment.image.repo }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: {{ .Values.deployment.container.portName }}
              containerPort: {{ .Values.deployment.container.port }}
          env:
            - name: spring_datasource_username
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets
                  key: spring_datasource_username
            - name: spring_datasource_password
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets
                  key: spring_datasource_password
            - name: spring_datasource_url
              valueFrom:
                secretKeyRef:
                  name: spring-datasource-secrets
                  key: spring_datasource_url
            - name: spring_rabbitmq_server
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: spring_rabbitmq_server
            - name: spring_rabbitmq_port
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: spring_rabbitmq_port
            - name: order_delivery_queue
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: order_delivery_queue
            - name: order_notification_queue
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: order_notification_queue
          livenessProbe:
            httpGet:
              port: {{ .Values.deployment.container.port }}
              path: /info/health
            initialDelaySeconds: {{ .Values.deployment.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              port: {{ .Values.deployment.container.port }}
              path: /info/status
            initialDelaySeconds: {{ .Values.deployment.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readiness.periodSeconds }}
