replicaCount: 2

deployment:
  name: notification-appl-deployment
  image:
    repo: yvzhelnin/notification-appl
    pullPolicy: Always
  label: notification-java-appl
  initContainer:
    name: init-pg
    image: busybox
  container:
    name: notification-pod-java
    portName: web
    port: 80
  readiness:
    initialDelaySeconds: 40
    periodSeconds: 5
    timeoutSeconds: 2
  liveness:
    initialDelaySeconds: 50
    periodSeconds: 5
service:
  name: notification-appl-service
  label: notification-appl-service-label
  type: NodePort
  protocol: TCP
  portName: service-web
  port: 8000

metrics:
  serviceMonitor:
    enabled: true
    interval: 15s
    path: /actuator/prometheus
