replicaCount: 1

app:
  withdrawUrl: http://billing-appl-service.crud-app.svc.cluster.local:8000/api/account/balance

deployment:
  name: order-appl-deployment
  image:
    repo: yvzhelnin/order-appl
    pullPolicy: Always
  label: order-java-appl
  initContainer:
    name: init-kafka
    image: busybox
  container:
    name: order-pod-java
    portName: web
    port: 80
  readiness:
    initialDelaySeconds: 40
    periodSeconds: 5
    timeoutSeconds: 2
  liveness:
    initialDelaySeconds: 50
    periodSeconds: 5
service:
  name: order-appl-service
  label: order-appl-service-label
  type: NodePort
  protocol: TCP
  portName: service-web
  port: 8000

rabbitmq:
  port: 5672
  deliveryQueue: delivery_messages
  notificationQueue: notification_messages
